/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arpirobot_Bridge */

#ifndef _Included_com_arpirobot_Bridge
#define _Included_com_arpirobot_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arpirobot_Bridge
 * Method:    BaseRobot_create
 * Signature: (Lcom/arpirobot/core/BaseRobot;)J
 */
JNIEXPORT jlong JNICALL Java_com_arpirobot_Bridge_BaseRobot_1create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_arpirobot_Bridge
 * Method:    BaseRobot_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_arpirobot_Bridge_BaseRobot_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_arpirobot_Bridge
 * Method:    BaseRobot_start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_arpirobot_Bridge_BaseRobot_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_arpirobot_Bridge
 * Method:    BaseRobot_feedWatchdog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_arpirobot_Bridge_BaseRobot_1feedWatchdog
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
